import profileImg from "../src/img/profile.jpg";

export const userData = [
  {
    name: "day 01",
    search_hits: 4000,
    pv: 2400,
    amt: 2400,
  },
  {
    name: "day 02",
    search_hits: 3000,
    pv: 1398,
    amt: 2210,
  },
  {
    name: "day 03",
    search_hits: 2000,
    pv: 9800,
    amt: 2290,
  },
  {
    name: "day 04",
    search_hits: 2780,
    pv: 3908,
    amt: 2000,
  },
  {
    name: "day 05",
    search_hits: 1890,
    pv: 4800,
    amt: 2181,
  },
  {
    name: "day 06",
    search_hits: 2390,
    pv: 3800,
    amt: 2500,
  },
  {
    name: "day 07",
    search_hits: 3490,
    pv: 4300,
    amt: 2100,
  },
  {
    name: "day 08",
    search_hits: 2490,
    pv: 4300,
    amt: 2100,
  },
  {
    name: "day 09",
    search_hits: 2390,
    pv: 4300,
    amt: 2100,
  },
  {
    name: "day 10",
    search_hits: 1190,
    pv: 4300,
    amt: 2100,
  },
  {
    name: "day 11",
    search_hits: 4690,
    pv: 4300,
    amt: 2100,
  },
  {
    name: "day 12",
    search_hits: 3200,
    pv: 4300,
    amt: 2100,
  },
];

export const userRows = [
  {
    id: 1,
    email: "Jon@gmail.com",
    user: "Jon Eric",
    login_rate: 35,
    status: "active",
    avatar: profileImg,
  },
  {
    id: 2,
    email: "Hsu@gmail.com",
    user: "Kelly Hsu",
    login_rate: 42,
    status: "active",
    avatar: profileImg,
  },
  {
    id: 3,
    email: "Perera@mail.com",
    user: "Kasun Perera",
    login_rate: 45,
    status: "inactive",
    avatar: profileImg,
  },
  {
    id: 4,
    email: "Stark@gmail.com",
    user: "Aravinda de Silva",
    login_rate: 16,
    status: "active",
    avatar: profileImg,
  },
  {
    id: 5,
    email: "Targaryen@netmail.com",
    user: "Ashan Wickramasingha",
    login_rate: null,
    status: "active",
    avatar: profileImg,
  },
  {
    id: 6,
    email: "Melisandre@unicef.com",
    user: "Denny Robert",
    login_rate: 150,
    status: "blocked",
    avatar: profileImg,
  },
  {
    id: 7,
    email: "Clifford@abclink.com",
    user: "Patric Mooray",
    login_rate: 44,
    status: "inactive",
    avatar: profileImg,
  },
  {
    id: 8,
    email: "Aluthwela@gmail.com",
    user: "Roshan Aluthwela",
    login_rate: 36,
    status: "active",
    avatar: profileImg,
  },
  {
    id: 9,
    email: "Roxie@mailnet.com",
    user: "Jenny Lowranz",
    login_rate: 65,
    status: "active",
    avatar: profileImg,
  },
];
